//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chude
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chude()
        {
            this.tblMusics = new HashSet<tblMusic>();
        }
    
        public int IDchude { get; set; }
        public string theloai1 { get; set; }
        public string theloai2 { get; set; }
        public string theloai3 { get; set; }
        public string idacc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMusic> tblMusics { get; set; }
    }
}
