//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhactt
    {
        public int idtt { get; set; }
        public Nullable<int> idnhac { get; set; }
        public Nullable<int> tamtrang { get; set; }
    
        public virtual tblMusic tblMusic { get; set; }
    }
}
