//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMusic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMusic()
        {
            this.nhactts = new HashSet<nhactt>();
        }
    
        public int iDmusic { get; set; }
        public string iDacc { get; set; }
        public string DisplayName { get; set; }
        public string Image { get; set; }
        public string Data { get; set; }
        public string Cotenttype { get; set; }
        public Nullable<int> luotnghe { get; set; }
        public string casi { get; set; }
        public Nullable<int> idchude { get; set; }
        public string Lyrics { get; set; }

        public virtual chude chude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhactt> nhactts { get; set; }
        public virtual tblAccount tblAccount { get; set; }
    }
}
